function newRule() {
  let randomRule = rules[Math.floor(Math.random() * rules.length)];
  document.getElementById("rule").innerHTML = randomRule;
}

function submit() {
    console.log("submitting!");
}

let rules = [
  "Eat food",
  "Don't eat anything your great grandmother wouldn't recognize as food",
  "Avoid food products containing ingredients that no ordinary human would keep in the pantry",
  "Avoid food products that contain high-fructose corn syrup",
  "Avoid food products that have some form of sugar (or sweetener) listed among the top three ingredients",
  "Avoid food products that have more than 5 ingredients",
  "Avoid food products containing ingredients that a third-grader cannot pronounce",
  "Avoid food products that make health claims",
  "Avoid food products with the word lite or the terms low fat or nonfat in their names",
  "Avoid foods that are pretending to be something they are not",
  "Avoid foods you see advertised on television",
  "Get out of the supermarket whenever you can (to buy food)",
  "Shop the peripheries of the supermarket and stay out of the middle",
  "Eat only foods that will eventually rot",
  "Eat foods made from ingredients that you can picture in their raw state or growing in nature",
  "Go food shopping every week",
  "Buy your snacks at the farmers market",
  "Eat Close to the Earth",
  "Eat only foods that have been cooked by humans",
  "Don't ingest foods made in places where everyone is required to wear a surgical cap",
  "If it came from a plant, eat it; if it was made in a plant, don't.",
  "It's not food if it arrived through the window of your car",
  "It's not food if it's called by the same name in every language (Think Big Mac, Cheetos or Pringles)",
  "When you eat real food, you don't need roles",
  "Eat mostly plants, especially leaves",
  "Treat meat as a flavoring or special occasion food",
  "Eating what stands on one leg [mushrooms and plant foods] is better than eating what stands on two legs [fowl], is better than eating what stands on four legs [cows, pigs and other mammals].",
  "Eat your colors",
  "Drink the spinach water",
  "Eat animals that have themselves eaten well",
  "If you have space, buy a freezer",
  "Eat like an omnivore (great diversity of species)",
  "Eat well-grown food from healthy soil",
  "Eat wild foods when you can",
  "Don't overlook the oily little fishes",
  "Eat some foods that have been predigested by bacterial or fungi",
  "Sweeten and salt your food yourself",
  "Eat sweet foods as you find them in nature",
  "Don't eat breakfast cereals that change the color of the milk",
  "Make water your beverage of choice",
  "Milk is a food, not a beverage",
  "The whiter the bread, the sooner you'll be dead",
  "Avoid sugary and starchy foods if you're concerned about weight",
  "Favor the kinds of oils and grains that have traditionally been stone ground",
  "Eat all the junk food you want as long as you cook it yourself",
  "Love your spices",
  "Be the kind of person who takes supplements - then skip the supplements",
  "Eat more lie the French. Or the Japanese. Or the Italians. Or the Greeks.",
  "Regard nontraditional foods with skepticism",
  "Avoid ingredients that lie to your body (artificial sweeteners and flavorings, starches, MMSG, texturizers)",
  "Enjoy drinks that have been caffeinated by nature not food science (coffee, tea)",
  "Have a glass of wine with dinner",
  "Pay more, eat less",
  "Eat less",
  "Stop eating before you're full",
  "Eat when you are hungry, not when you are bored",
  "If you're not hungry enough to eat an apple, then you're probably not hungry",
  "It's okay to be a little hungry",
  "Don't let yourself get too hungry",
  "Consult your gut (slow down and pay attention what your body is telling you)",
  "Serve the vegetables first",
  "Eat slowly (enough to savor your food; you'll need less of it to be satisfied)",
  "The banquet is in the first bite",
  "Spend as much time enjoying the meal as it took to prepare it",
  "Give some thought to where your food comes from",
  "Don't become a short order cook",
  "Buy smaller plates and glasses",
  "Serve a proper portion and don't go back for seconds",
  "Order the small (in a restaurant)",
  "Breakfast like a king, lunch like a prince, dinner like a pauper",
  "Eat meals (snacking less)",
  "Limit your snacks to unprocessed plant foods",
  "Do all your eating at a table",
  "Don't get your fuel from the same place your car does",
  "No labels on the table (keep logos and food packaging off the dinner table)",
  "Place a bouquet of flowers on the table and everything will taste twice as good",
  "Leave something on your plate",
  "Eat with other people whenever you can",
  "Treat treats as treats",
  "Compost",
  "Plant a vegetable garden if you have space, a window box if you don't",
  "Cook",
  "Break the rules once in a while",
];
